### ISSUE TITLE
Index out of range error in strace.go parseEnterSyscall()

### ISSUE THREAD

**Issue by maxfisher-g** [ossf/package-analysis#477]
Found when running analysis on package `temps` v0.0.8 from NPM. Attached package tarball for reproducibility: [temps-0.0.8.tar.gz](https://github.com/ossf/package-analysis/files/10127982/temps-0.0.8.tar.gz)

```

panic: runtime error: index out of range [2] with length 0

goroutine 1 [running]:
github.com/ossf/package-analysis/internal/strace.(*Result).parseEnterSyscall(0xc000d1a180, {0xc0004b25e4?, 0x5e?}, {0xc0004b25ea?, 0x2b?})
	/src/internal/strace/strace.go:182 +0x2e6
github.com/ossf/package-analysis/internal/strace.Parse({0x163db40?, 0xc0000140a0})
	/src/internal/strace/strace.go:335 +0x2a9
github.com/ossf/package-analysis/internal/dynamicanalysis.Run({0x16469a0, 0xc000a9ccc0}, {0xc000a9cd20, 0x5, 0x6})
	/src/internal/dynamicanalysis/analysis.go:108 +0x609
github.com/ossf/package-analysis/internal/worker.RunDynamicAnalysis({0x16469a0, 0xc000a9ccc0}, 0xc00004c780)
	/src/internal/worker/rundynamic.go:39 +0x4d6
main.dynamicAnalysis(0xc00004c780)
	/src/cmd/analyze/main.go:93 +0xe5
main.main()
	/src/cmd/analyze/main.go:209 +0xb45
```

**Comment by maxfisher-g** [comment]
Fixed by #483
